### ISSUE TITLE
Reconcile with rules_docker?

### ISSUE THREAD

**Issue by mattmoor** [guymers/bazel_rules_container_test#1]
It looks like this is based on a *really* old fork of [rules_docker](https://github.com/bazelbuild/rules_docker) (from when it was bundled with Bazel core).  This is missing out on a significant number of additions/improvements including: `docker_push`, `docker_pull`, as well as some significant speed improvements.

Not sure what your original motivations were for forking, but I'd love to have a conversation about joining forces.  Happy to discuss here, or if you want to reach out to my github handle @google.com

**Comment by guymers** [comment]
Reconciliation would be great now that the Docker rules are split out of Bazel and getting new functionality.

The reasons for this fork where:
 - I wanted to try having separate `layer` and `image` rules (https://github.com/bazelbuild/bazel/issues/1113#issuecomment-221539665)
 - I wanted to build generalised OCI images; but rkt still doesn't natively support them
 - I wanted to be able to test containers

If there is anything in this repo that you would like in Docker rules let me know and I'll open a PR.

**Comment by mattmoor** [comment]
I'm not 100% clear on the value of splitting layer / image, it is something I'd be happy to discuss (I don't want to hijack this for that discussion though).

We're planning to add OCI support to the underlying Python library fairly soon, so I'd expect OCI support in `rules_docker` to follow.

Regarding testing, @dlorenc and team have created some neat `structure_test` rules, which enable testing containers built using `docker_build`, which we use extensively to test samples in our [distroless](https://github.com/googlecloudplatform/distroless) repo.  Perhaps we should think about moving these into `rules_docker` to give them some better exposure.


I can't say I've exhaustively probed your fork (yet), but I think the area where this repo has clearly advanced things is multi-format support, so I'd love your input on the same for how we evolve `rules_docker`.  For instance, it has been a while since I looked at `rkt`.  I'll open an issue on `rules_docker` for discussing how we evolve things to better support multiple-container formats.

**Comment by mattmoor** [comment]
FYI https://github.com/bazelbuild/rules_docker/issues/110

**Comment by guymers** [comment]
One benefit of having the split between layer and image is it allows you to "mixin" layers. This can help if you have a complex layer that you want in multiple containers without requiring them all to extend a base container that contains it (https://github.com/guymers/containers_by_bazel/blob/master/base/ca_certificates/BUILD). 
It also allows you to build containers that require multiple executables. For example if I have the following container structure:
```
base  <- java    <- sbt
      <- nodejs
```
and I wanted to build a container with `sbt` and `nodejs` for testing a ScalaJS project I could create a container based on `sbt` and add the same layers used to build the `nodejs` container.
Also the build rule can be defined using on them. 

I am using the Go interfaces from https://github.com/opencontainers/image-spec to create the config json files. I don't know if you want to consider using them as well?

I have only had a quick look at the `structure_test` rules so I can't comment on if it would solve my use case. The rules I have either `docker run` a provided shell script or `docker exec` on a running container depending on a `daemon` flag. The output is then compared to an expected output file. I will have a deeper look at the `structure_test` soon.

**Comment by guymers** [comment]
Given `docker_rules` has `container_layer` and `container_image` I have removed those and updated `container_test` to build on top of `docker_rules`
